// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKO9e-yaMoB-N0vb8LUDlxXL4yr_Svs-g',
    appId: '1:136225829076:web:095bb7cfd77003aeddcb41',
    messagingSenderId: '136225829076',
    projectId: 'base-pro-b0a43',
    authDomain: 'base-pro-b0a43.firebaseapp.com',
    databaseURL: 'https://base-pro-b0a43-default-rtdb.firebaseio.com',
    storageBucket: 'base-pro-b0a43.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj5DO4_wjh4w2R0rol_UgYOFrbP-FM6XM',
    appId: '1:136225829076:android:3f2241b8338e2533ddcb41',
    messagingSenderId: '136225829076',
    projectId: 'base-pro-b0a43',
    databaseURL: 'https://base-pro-b0a43-default-rtdb.firebaseio.com',
    storageBucket: 'base-pro-b0a43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkGBUKYPVRXUmuyo-hf4kShyYmDxD4_4c',
    appId: '1:136225829076:ios:e6b85fbf29c5bd73ddcb41',
    messagingSenderId: '136225829076',
    projectId: 'base-pro-b0a43',
    databaseURL: 'https://base-pro-b0a43-default-rtdb.firebaseio.com',
    storageBucket: 'base-pro-b0a43.appspot.com',
    iosBundleId: 'com.example.pfeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkGBUKYPVRXUmuyo-hf4kShyYmDxD4_4c',
    appId: '1:136225829076:ios:e6b85fbf29c5bd73ddcb41',
    messagingSenderId: '136225829076',
    projectId: 'base-pro-b0a43',
    databaseURL: 'https://base-pro-b0a43-default-rtdb.firebaseio.com',
    storageBucket: 'base-pro-b0a43.appspot.com',
    iosBundleId: 'com.example.pfeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKO9e-yaMoB-N0vb8LUDlxXL4yr_Svs-g',
    appId: '1:136225829076:web:03f1d92ec0b730b9ddcb41',
    messagingSenderId: '136225829076',
    projectId: 'base-pro-b0a43',
    authDomain: 'base-pro-b0a43.firebaseapp.com',
    databaseURL: 'https://base-pro-b0a43-default-rtdb.firebaseio.com',
    storageBucket: 'base-pro-b0a43.appspot.com',
  );
}
